const { chromium } = require(process.env.PLAYWRIGHT_MODULE || '@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
 const base=process.env.BASE_URL||'http://127.0.0.1:8765';
 const endpoint=process.env.STATIC_DATA?'data/current.json':'api/gold';
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 await page.goto(base+'/');
 for(const id of ['gold-long-chart','chart','gold-silver-chart','btc-gold-chart','mining-trend','reserves-trend','market-cap-chart','gold-debt-chart','gold-stock-chart','mining-stock-chart'])await page.waitForSelector(`#${id} svg`).catch(async error=>{console.error({chart:id,errors,status:await page.locator('#status').textContent(),research:await page.locator('#research-status').textContent()});throw error;});
 assert.equal(requests.filter(u=>u.endsWith('/'+endpoint)).length,1);
 assert.ok(requests.every(u=>u.startsWith(base+'/')));
 assert.match(await page.locator('#range').textContent(),/1960-01/);
 // Value Compass shell and cross-links: one script execution, registry deep links with theme/from.
 assert.equal(await page.evaluate(()=>!!document.querySelector('vc-shell').shadowRoot&&window.VCShell.version),'1.1.0');
 assert.equal(await page.evaluate(()=>performance.getEntriesByType('resource').filter(e=>e.initiatorType==='script').length),await page.evaluate(()=>new Set(performance.getEntriesByType('resource').filter(e=>e.initiatorType==='script').map(e=>e.name)).size));
 assert.match(await page.locator('#etf-cards a.ecosystem-link').first().getAttribute('href'),/eiayn\/\?code=411060&theme=(light|dark)&from=all-about-gold$/);
 assert.match(await page.locator('.krx-conditions a.ecosystem-link').getAttribute('href'),/gold_gap\/\?asset=gold&theme=(light|dark)&from=all-about-gold$/);
 await page.locator('#chart').focus();await page.keyboard.press('Home');assert.match(await page.locator('#tooltip').textContent(),/비트코인 자료 없음/);
 await page.locator('#alignment').selectOption('common');assert.match(await page.locator('#range').textContent(),/2014-10/);
 await page.locator('#alignment').selectOption('independent');await page.locator('[data-period="30"]').click();assert.match(await page.locator('#range').textContent(),/1996-08/);
 await page.locator('[data-period="all"]').click();
 await page.locator('#gold-period').selectOption('30');assert.match(await page.locator('#gold-range').textContent(),/1996/);await page.locator('#gold-period').selectOption('all');
 await page.locator('#mode').selectOption('return');assert.ok(await page.locator('#log').isDisabled());await page.locator('#mode').selectOption('index');await page.locator('#log').check();
 await page.locator('#ratio-period').selectOption('5');assert.match(await page.locator('#btc-gold-tip').textContent(),/2021/);await page.locator('#ratio-period').selectOption('all');
 await page.locator('#reserve-country').selectOption('KR');assert.equal(await page.locator('#reserves-trend polyline').count(),1);await page.locator('#reserve-log').check();
 await page.locator('#reserve-country').selectOption('all');
 await page.locator('#mining-region').selectOption('us');assert.equal(await page.locator('#mining-trend polyline').getAttribute('data-series'),'us');
 await page.locator('#country-search').fill('한국');assert.equal(await page.locator('#reserve-rows tr').count(),1);await page.locator('#country-search').fill('');
 await page.locator('[data-type="금광주형"]').click();assert.equal(await page.locator('.etf-card').count(),1);await page.locator('#etf-market').selectOption('한국');assert.match(await page.locator('#etf-cards').textContent(),/없습니다/);
 await page.locator('[data-type="전체"]').click();await page.locator('#etf-market').selectOption('전체');
 assert.equal(await page.locator('.methods-table tbody tr').count(),5);
 const download=page.waitForEvent('download');await page.locator('#download').click();const file=await download;
 assert.match(file.suggestedFilename(),/1960-01/);const csv=fs.readFileSync(await file.path(),'utf8');assert.match(csv.split('\r\n')[1],/"1960-01","35","0.9","",""/);
 await page.locator('#market-size-period').selectOption('10');await page.locator('#market-size-log').uncheck();await page.locator('#market-size-period').selectOption('all');
 await page.locator('#stock-period').selectOption('20');await page.locator('#stock-period').selectOption('all');
 assert.equal(await page.locator('#market-size-rows tr').count(),126);
 const annualDownload=page.waitForEvent('download');await page.locator('#download-market-size').click();const annualCsv=fs.readFileSync(await (await annualDownload).path(),'utf8');assert.match(annualCsv,/1900,35104,386,,,,/);
 await page.locator('#market-size').screenshot({path:'artifacts/market-size.png'});
 await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
 for(const width of [390,768]){
  await page.setViewportSize({width,height:844});await page.goto(base+'/?theme=dark');await page.waitForSelector('#reserves-trend svg');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 }
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
 await page.goto(base+'/?embed=0&theme=light');await page.waitForSelector('#chart svg');assert.equal(await page.locator('.topbar').isVisible(),true);
 await page.goto(base+'/?embed=overview&theme=light');await page.waitForSelector('#chart svg');assert.equal(await page.locator('.topbar').isVisible(),false);assert.equal(await page.locator('vc-shell').isVisible(),false);
 await page.route('**/'+endpoint,route=>route.fulfill({status:503,body:'Unavailable'}));await page.reload();await page.locator('#status button').waitFor();assert.match(await page.locator('#status').textContent(),/finance-pi/);
 await page.unroute('**/'+endpoint);await page.locator('#status button').click();await page.waitForSelector('#gold-long-chart svg');await page.locator('#research-status button').click();await page.waitForSelector('#reserves-trend svg');
 assert.deepEqual(errors,[]);await browser.close();console.log('Browser checks passed: finance-pi-only fetch, all historical charts, missing data, filters, CSV, mobile, embed, failure/retry.');
})().catch(e=>{console.error(e);process.exit(1)});
